services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: always
    networks:
      - courses-net
    volumes:
      - ./staticfiles:/app/static
      - ./media:/app/media
      - ./logs:/app/logs
      - ./nginx:/etc/nginx/conf.d
    expose:
      - 8088
    ports:
      - "80:8088"
    depends_on:
      - courses


  courses:
    build: .
    image: courses
    container_name: courses
    restart: always
    command: "gunicorn -c gunicorn.py base.wsgi"
    networks:
      - courses-net
    volumes:
      - .:/app
#      - ./db:/app/db     --Этой бд больше нет. НЕЗАБУДЬ ИСПРАВИТЬ, ЗАХАР!!
    ports:
      - "8000:8000"

networks:
  courses-net:
    driver: bridge