# Generated by Django 5.1.7 on 2025-03-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_rename_lecturers_course_lecturer_course_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="poster",
            field=models.ImageField(
                default=1, upload_to="courses_images/", verbose_name="Постер"
            ),
            preserve_default=False,
        ),
    ]
