# Generated by Django 5.1.7 on 2025-03-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_course_poster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
