# Generated by Django 5.1.7 on 2025-03-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_cartitem_price_alter_course_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="reviews_qty",
        ),
    ]
