# Generated by Django 5.2 on 2025-04-14 11:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_remove_course_reviews_qty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
